environment:
  PYTHON: "C:\\Python37-x64"

install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - "%PYTHON%\\python -m pip install -U setuptools twine wheel cibuildwheel cython"

before_build:
  # Remove git from path
  - set PATH=%PATH:C:\Program Files\Git\usr\bin;=%
  - set PATH=C:\MinGW\bin;C:\msys64\usr\bin;%PATH%
  - mkdir "%APPVEYOR_BUILD_FOLDER%\\re2\\builddir"
  - cd "%APPVEYOR_BUILD_FOLDER%\\re2\\builddir"
  - cmake .. -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_INSTALL_PREFIX="%APPVEYOR_BUILD_FOLDER%\\pyre2\\re2" -DRE2_BUILD_TESTING=OFF
  - cmake --build . --target install --config Release
  - cd "%APPVEYOR_BUILD_FOLDER%\\pyre2"
  - SET HOME=%HOMEPATH%
  - "patch -p1 < ..\\windows\\setup.py.patch"
  - "%PYTHON%\\python setup.py build"

build_script:
  - cd "%APPVEYOR_BUILD_FOLDER%\\pyre2"
  - cibuildwheel --output-dir wheelhouse

artifacts:
  - path: "apsw\\wheelhouse\\*.whl"
    name: Wheels
